---
area/dependencies:
  - "Dockerfile"
  - "go.mod"
  - "go.sum"
area/tooling:
  - ".github/**/*"
  - "Dockerfile"
area/docs:
  - "CODE-OF-CONDUCT.md"
  - "CONTRIBUTING.md"
  - "DCO"
  - "LICENSE"
  - "README.md"
