---
"area/dependencies":
  - changed-files:
      - any-glob-to-any-file:
          [
            "Dockerfile",
            "go.mod",
            "go.sum",
          ]
"area/tooling":
  - changed-files:
      - any-glob-to-any-file:
          [
            ".github/**/*",
            "Dockerfile",
          ]
"area/docs":
  - changed-files:
      - any-glob-to-any-file:
          [
            "CODE-OF-CONDUCT.md",
            "CONTRIBUTING.md",
            "DCO",
            "LICENSE",
            "README.md",
          ]
