---
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/prom-authzed-proxy"
linters:
  enable:
    - "deadcode"
    - "errcheck"
    - "gofumpt"
    - "goimports"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "typecheck"
    - "unused"
    - "varcheck"
