name: "Build & Test"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.16"
    - name: "Go Mod Tidy"
      run: |
        GO_MOD_OUPUT="$(go mod tidy -v 2>&1)"
        if [[ $GO_MOD_OUPUT == *"unused"* ]]; then
          echo "${GO_MOD_OUPUT}"
          exit 1
        fi
    - name: "Formatting (gofumpt)"
      run: |
        go install mvdan.cc/gofumpt/gofumports@v0.1.1
        GOFUMPT_OUTPUT="$(gofumports -d .)"
        if [ -n "$GOFUMPT_OUTPUT" ]; then
          echo "All the following files are not correctly formatted"
          echo "${GOFUMPT_OUTPUT}"
          exit 1
        fi
    - name: "Linting (revive)"
      run: |
        go install github.com/mgechev/revive@latest
        revive ./...
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-go@v2"
      with:
        go-version: "^1.16"
    - name: "Build"
      run: "go build ."
    - name: "Test"
      run: "go test ./..."
